### ISSUE TITLE
Some pastes fail

### ISSUE THREAD

**Issue by Arovei** [Quzzar/TalesTerrain#2]
When pasting some of the slabs in, as you get closer to board level the paste fails to load. You see a flicker as if something tried to happen, but the slab doesn't appear.

![image](https://user-images.githubusercontent.com/5642569/120085846-7af7d380-c0a9-11eb-8e2d-9ecb87bccf35.png) 
![image](https://user-images.githubusercontent.com/5642569/120085812-471cae00-c0a9-11eb-8e13-8e5923c56232.png)
With those settings and heightmap, map to tile height 40, biomes on and fill ground off.

Slabs 1-49 work fine, but 50-64 fail to work.

Same issue happened with another heightmap generated by the website itself
![image](https://user-images.githubusercontent.com/5642569/120085882-e2ae1e80-c0a9-11eb-8517-643d46bad093.png)
![image](https://user-images.githubusercontent.com/5642569/120085890-083b2800-c0aa-11eb-95d6-c059845f2b4e.png)

but in this case only slabs 70 + 71 failed to work.

**Comment by Quzzar** [comment]
Thanks for the detailed report! The bug should now be fixed.
